//
//  PTSStyleKit.h
//  PTSD Coach
//
//  Created by  on 2015-12-03.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PTSStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* audioPlayButtonImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* audioPauseButtonImageTargets;

// Generated Images
+ (UIImage*)imageOfAudioPlayButtonImage;
+ (UIImage*)imageOfAudioPauseButtonImage;

@end
