//
//  PTSStyleKit.m
//  PTSD Coach
//
//  Created by  on 2015-12-03.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PTSStyleKit.h"


@implementation PTSStyleKit

#pragma mark Cache

static UIImage* _imageOfAudioPlayButtonImage = nil;
static UIImage* _imageOfAudioPauseButtonImage = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawAudioPlayButtonImage
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Play Image Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 17, 18);
    CGContextRotateCTM(context, -270 * M_PI / 180);

    UIBezierPath* playImagePath = [UIBezierPath bezierPath];
    [playImagePath moveToPoint: CGPointMake(0, -12)];
    [playImagePath addLineToPoint: CGPointMake(10.39, 6)];
    [playImagePath addLineToPoint: CGPointMake(-10.39, 6)];
    [playImagePath closePath];
    [UIColor.blackColor setFill];
    [playImagePath fill];

    CGContextRestoreGState(context);
}

+ (void)drawAudioPauseButtonImage
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(9, 8, 6, 20)];
    [UIColor.blackColor setFill];
    [rectanglePath fill];


    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(21, 8, 6, 20)];
    [UIColor.blackColor setFill];
    [rectangle2Path fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfAudioPlayButtonImage
{
    if (_imageOfAudioPlayButtonImage)
        return _imageOfAudioPlayButtonImage;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(36, 36), NO, 0.0f);
    [PTSStyleKit drawAudioPlayButtonImage];

    _imageOfAudioPlayButtonImage = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfAudioPlayButtonImage;
}

+ (UIImage*)imageOfAudioPauseButtonImage
{
    if (_imageOfAudioPauseButtonImage)
        return _imageOfAudioPauseButtonImage;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(36, 36), NO, 0.0f);
    [PTSStyleKit drawAudioPauseButtonImage];

    _imageOfAudioPauseButtonImage = [UIGraphicsGetImageFromCurrentImageContext() imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfAudioPauseButtonImage;
}

#pragma mark Customization Infrastructure

- (void)setAudioPlayButtonImageTargets: (NSArray*)audioPlayButtonImageTargets
{
    _audioPlayButtonImageTargets = audioPlayButtonImageTargets;

    for (id target in self.audioPlayButtonImageTargets)
        [target performSelector: @selector(setImage:) withObject: PTSStyleKit.imageOfAudioPlayButtonImage];
}

- (void)setAudioPauseButtonImageTargets: (NSArray*)audioPauseButtonImageTargets
{
    _audioPauseButtonImageTargets = audioPauseButtonImageTargets;

    for (id target in self.audioPauseButtonImageTargets)
        [target performSelector: @selector(setImage:) withObject: PTSStyleKit.imageOfAudioPauseButtonImage];
}


@end
